/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_CppDllLibrary */

#ifndef _Included_model_CppDllLibrary
#define _Included_model_CppDllLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_CppDllLibrary
 * Method:    convertToNegative
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_model_CppDllLibrary_convertToNegative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     model_CppDllLibrary
 * Method:    convertToSepia
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_model_CppDllLibrary_convertToSepia
  (JNIEnv *, jobject, jobjectArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
