/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_CDllLibrary */

#ifndef _Included_model_CDllLibrary
#define _Included_model_CDllLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_CDllLibrary
 * Method:    convertToNegative
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_model_CDllLibrary_convertToNegative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     model_CDllLibrary
 * Method:    convertToSepia
 * Signature: ([[I)V
 */
JNIEXPORT void JNICALL Java_model_CDllLibrary_convertToSepia
  (JNIEnv *, jobject, jobjectArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
